# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
#use_frameworks!

target 'IronSourceDemoApp' do
  pod 'IronSourceSDK', '~> 7.2.1.2'
  pod 'tempo-ironsource-mediation', :path => '../'
#  pod 'tempo-ironsource-mediation', '~> 0.0.2'

end
